### ISSUE TITLE
[Docker] Can't use it with SF Docker template

### ISSUE THREAD

**Issue by LaurentSanson** [sensiolabs/GotenbergBundle#131]
Hi guys,

I've been trying to use your bundle in a SF project ([from this repo](https://github.com/dunglas/symfony-docker)) and I can't use it with the default config... Can anyone help me with an updated config to make it usable?

```
Failed to connect to localhost port 3000 after 0 ms: Couldn't connect to server for "http://localhost:3000/forms/chromium/convert/html".
```

I've tried to change the GOTENBERG_DSN to add https but still got the error

**Comment by Jean-Beru** [comment]
Hello @LaurentSanson!

It seems that you've spotted a bug in the recipe. The DSN should be `http://gotenberg:3000` since `gotenberg` is the name of the service and the defined port is `3000`. See https://github.com/symfony/recipes-contrib/blob/main/sensiolabs/gotenberg-bundle/0.1/manifest.json#L9.

Can you confirm that this DSN works for you? We could update the recipe if everything is OK (or you can make your own PR in the recipe repository).

**Comment by LaurentSanson** [comment]
Hey @Jean-Beru !

Thanks for the quick feedback even during this time of the year 😄 

I can confirm that it is now working properly.

Yes I'll make the PR if you want

**Comment by Jean-Beru** [comment]
Wow! So quick :rocket: 

Thanks @LaurentSanson!

> Thanks for the quick feedback even during this time of the year 😄

My holidays start next week :stuck_out_tongue:
